
from os import environ

# CONSUMER_KEY = environ['CONSUMER_KEY'] 
# CONSUMER_SECRET = environ['CONSUMER_SECRET'] 
# ACCESS_KEY =  environ['ACCESS_KEY']
# ACCESS_SECRET =  environ['ACCESS_SECRET']

CONSUMER_KEY = "pDbJJIRpe3WJWBcwmIJpmbFBo"
CONSUMER_SECRET = "SSTzciE3cOaADC6BcLXMWXmf8QzbN2jA9oUiP9rccA7oAtRgPM"
ACCESS_KEY = "1388994641484292101-DN5pVJzlP3whtcJv6spgL1RGLMYHgi"
ACCESS_SECRET = "lBNWbWkSdx7hTjuCEG2GLeDuovWXNw9tC5utv3E9gvVMw"